# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AOUN' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AOUN

  target 'AOUNTests' do
    inherit! :search_paths
    pod 'Firebase'
  end

  target 'AOUNUITests' do
    # Pods for testing
  end

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'

  pod 'RPTTextView'

  
  pod 'IQKeyboardManagerSwift', '~> 6.5'

end
